# docker-compose.yml
version: '3.8'

services:
  web:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: unicampus_flask_app
    ports:
      - "5000:8000" # Map host port 5000 to container port 8000 (where Gunicorn runs)
    volumes:
      - .:/app    # Mount current directory into /app in container for live code changes
                  # For production, you typically wouldn't mount the code like this after building.
    env_file:
      - .env      # Load environment variables from .env file
    environment:
      - FLASK_ENV=development # Override FLASK_ENV for local development
      - FLASK_DEBUG=1         # Enable Flask debug mode for local development
    depends_on:
      - mongo
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"] # Override CMD for dev: use Flask dev server

  mongo:
    image: mongo:latest # Use official MongoDB image
    container_name: unicampus_mongo_db
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

volumes:
  mongo_data: # Defines a named volume for MongoDB data persistence