services:
  flask_app:
    build:
      context: ./flask_service
      dockerfile: Dockerfile
    container_name: unicampus_flask_service
    ports:
      - "5000:8000"
    volumes:
      - ./flask_service:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - mongo
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]

  mongo:
    image: mongo:latest
    container_name: unicampus_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: