# .github/workflows/ci.yml

name: UniCampus Backend CI/CD

on:
  push:
    branches:
      - main # Analyze main branch on push
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'
      - 'devops/**'
  pull_request:
    types: [opened, synchronize, reopened] # Analyze PRs against main
    branches:
      - main

jobs:
  build-lint-test-analyze: # Renamed job for clarity
    name: Build, Lint, Test & Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # SonarCloud needs full history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov # For linting and testing

      - name: Lint with Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run Tests with Pytest (and generate coverage)
        run: |
          # Create a 'tests' directory and add test files (e.g., tests/test_example.py)
          # This command will pass even if no tests are found initially due to '|| true'
          pytest --cov=app --cov-report=xml:coverage.xml --cov-report=term-missing || true
          # IMPORTANT: Remove '|| true' once you have actual tests that should pass.

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master # Dedicated SonarCloud action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub, required for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # Your SonarCloud analysis token from GitHub secrets
        with:
          # projectBaseDir: . # Defaults to current directory, usually fine
          args: > # Pass Sonar analysis parameters here
            -Dsonar.organization=iamsjeevan
            -Dsonar.projectKey=iamsjeevan_unicampus-backend
            -Dsonar.python.coverage.reportPaths=coverage.xml
            # -Dsonar.sources=app  # Uncomment if your source code is primarily in the 'app' directory
            # -Dsonar.verbose=true # Uncomment for more detailed scanner logs if troubleshooting

  build-and-push-docker-image:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    needs: build-lint-test-analyze # Run only if the previous job succeeds
    # Only run this step on pushes/merges to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/unicampus-backend:latest
            ghcr.io/${{ github.repository_owner }}/unicampus-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max